env:
  node: true
  browser: false
  commonjs: true
  es6: true
  mocha: true
extends:
  - eslint:recommended
parser: "@babel/eslint-parser"
parserOptions:
  babelOptions:
    configFile: './.babelrc'
  ecmaVersion: 2018
plugins:
  - "@babel"
rules: {}
